services:
  VPN:
    ports:
      - 8888:8888/tcp # Gluetun Local Network HTTP proxy
      - 8388:8388/tcp # Gluetun Local Network Shadowsocks
      - 8388:8388/udp # Gluetun Local Network Shadowsocks
      - 5572:5572/tcp # rclone
     # - 8282:8282 # qBittorrent blackhole
     # - 8181:8181 # Proxy blackhole
#      Zurg
      - 9999:9999
#      Dozzle
      - 8099:8080
#      Homepage
      - 3001:3000
#      Filebrowser
      - 8095:80
     # Riven Frontend
      - 3000:3000
     # Riven Backend
      - 8080:8080
     # RDT client
      - 6500:6500
     # The Arrs_________________________
      - ${WEBUI_PORT_PROWLARR:?err}:9696
      - ${WEBUI_PORT_BAZARR:?err}:6767
      - ${WEBUI_PORT_LIDARR:?err}:8686
      - ${WEBUI_PORT_RADARR:?err}:7878
      - ${WEBUI_PORT_READARR:?err}:8787
      - ${WEBUI_PORT_SONARR:?err}:8989
      - ${WEBUI_PORT_WHISPARR:?err}:6969
      - ${WEBUI_PORT_JELLYFIN:?err}:8096
      - ${WEBUI_PORT_JELLYSEERR:?err}:5055
      - ${WEBUI_PORT_QBITTORRENT:?err}:${WEBUI_PORT_QBITTORRENT:?err}
      - ${FLARESOLVERR_PORT:?err}:8191
      - ${TDARR_SERVER_PORT:?err}:${TDARR_SERVER_PORT:?err}
      - ${WEBUI_PORT_TDARR:?err}:${WEBUI_PORT_TDARR:?err}
      - ${WEBUI_PORT_PLEX:?err}:32400
      - 1900:1900/udp # DNLA Service
      - 5343:5343/udp # Plex Network Port
      - 8324:8324 # Plex Network Port
      - 32410:32410/udp # Plex Network Port
      - 32412:32412/udp # Plex Network Port
      - 32413:32413/udp # Plex Network Port
      - 32414:32414/udp # Plex Network Port
      - 32469:32469 # Plex Network Port
  zurg:  
    network_mode: service:VPN
    ports: !reset
      - []
  rclone:
    network_mode: service:VPN
    ports: !reset
      - [] 
  homepage:
    network_mode: service:VPN
    ports: !reset
      - [] 
  filebrowser:
    network_mode: service:VPN
    ports: !reset
      - []
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
  dozzle:
    network_mode: service:VPN
    ports: !reset
      - [] 