networks:
  VPN:
    name: VPN
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:?err}
          gateway: ${DOCKER_GATEWAY:?err}
include:
  - compose/individual/docker-compose-gluetunVPN.yaml
  - compose/individual/docker-compose-zurg.yaml