services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${PUID} # optional, your user id
      PGID: ${PGID} # optional, your group id
    ports:
      - 3000:3000
    volumes:
      - ${APPDATA}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped