services:
  homepage:
    container_name: homepage
    network_mode: container:VPN
    environment:
      - TZ=America/Los_Angeles
      - HOST_OS=Unraid
      - HOST_HOSTNAME=whiskeyshits
      - HOST_CONTAINERNAME=homepage
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:3001
      - net.unraid.docker.icon=https://raw.githubusercontent.com/gethomepage/homepage/main/public/android-chrome-512x512.png
    #ports:
    #  - 3001:3000/tcp
    volumes:
      - /mnt/user/appdata/homepage:/app/config:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    network_mode: container:VPN
    volumes:
      - /mnt/user/:/srv #Change to match your directory
      - ${APPDATA}/filebrowser/filebrowser.db:/database/filebrowser.db:rw #Change to match your directory
      - ${APPDATA}/filebrowser/settings.json:/config/settings.json:rw #Change to match your directory
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
   # ports:
   #   - 8095:80 #Change the port if needed
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:8095
      - net.unraid.docker.icon=https://github.com/maschhoff/docker/raw/master/filebrowser/35781395.png
      - homepage.group=Utilites
      - homepage.name=FileBrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://${SERVER_IP}:8095
      - homepage.description=Media server

