services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t
    volumes:
    # config dirs
      - ${APPDATA}/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup.
      - ${APPDATA}/DMB/log:/log                           ## Location for logs
      - ${APPDATA}/DMB/Zurg/RD:/zurg/RD                   ## Location for Zurg RealDebrid active configuration
      - ${APPDATA}/DMB/PostgreSQL/data:/postgres_data     ## Location for PostgreSQL database if using Riven
      - ${APPDATA}/DMB/Zilean/data:/zilean/app/data       ## Location for Zilean data if using Riven
      - ${APPDATA}/DMB/Riven/data:/riven/backend/data     ## Location for Riven backend data
    # media dirs
      - ${ZURG}:/data:shared           ## Location for rclone mount to host
      - ${RIVEN}:/mnt                  ## Location for Riven symlinks

    environment:
      - TZ=${TIMEZONE:?err}
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - COLOR_LOG_ENABLED=true
      - PLEX_TOKEN=${PLEX_CLAIM}
      - PLEX_ADDRESS=${SERVER_IP}:32400
      - ZURG_ENABLED=true
      - RD_API_KEY=${REALDEBRID_API}
      - RCLONE_MOUNT_NAME=DMB
      - ZILEAN_ENABLED=true
      - RIVEN_ENABLED=true
      - ORIGIN={SERVER_IP}:3000                                  ## See Riven documentation for more details
    # network_mode: container:gluetun                            ## Example to attach to gluetun vpn container if realdebrid blocks IP address
    ports:
      - 3000:3000
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
# Add Configurations for GPU Hardware Rendering Here:
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${APPDATA}/plex/library:/config
      - ${MEDIA}/tv:/mnt/tv
      - ${MEDIA}/movies:/mnt/movies
      - ${MEDIA}/transcode:/mnt/transcode
      - ${ZURG}:/mnt/zurg            ## rclone mount location from DMB must be shared to Plex container. Don't add to plex library
      - ${RIVEN}:/mnt/riven            ## Riven symlink location from DMB must be shared to Plex container. Add to plex library
    ports:
      - 32400:32400
      - 1900:1900/udp
     # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - DOCKER_MODS=${DOCKER_MODS}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=plex
      - TAILSCALE_AUTHKEY=${TS_KEY}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
   # depends_on:                                            ## Used to delay the startup of plex to ensure the rclone mount is available.
    #  DMB:                                                 ## set to the name of the container running rclone
    #    condition: service_healthy