services:
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t
    volumes:
    # config dirs
      - /mnt/user/appdata/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup.
      - /mnt/user/appdata/DMB/log:/log                           ## Location for logs
      - /mnt/user/appdata/DMB/Zurg/RD:/zurg/RD                   ## Location for Zurg RealDebrid active configuration
      - /mnt/user/appdata/DMB/PostgreSQL/data:/postgres_data     ## Location for PostgreSQL database if using Riven
      - /mnt/user/appdata/DMB/Zilean/data:/zilean/app/data       ## Location for Zilean data if using Riven
      - /mnt/user/appdata/DMB/Riven/data:/riven/backend/data     ## Location for Riven backend data
    # media dirs
      - /mnt/user/data/media/DMB/Zurg:/data:shared           ## Location for rclone mount to host
      - /mnt/user/data/media/DMB/Riven:/mnt                  ## Location for Riven symlinks

    environment:
      - TZ=${TIMEZONE:?err}
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - COLOR_LOG_ENABLED=true
      - PLEX_TOKEN=${PLEX_CLAIM}
      - PLEX_ADDRESS=${PLEX_IP}:32400
      - ZURG_ENABLED=true
      - RD_API_KEY=${REALDEBRID_API}
      - RCLONE_MOUNT_NAME=DMB
      - ZILEAN_ENABLED=true
      - RIVEN_ENABLED=true
      - ORIGIN={SERVER_IP}:3000                                  ## See Riven documentation for more details
    # network_mode: container:gluetun                            ## Example to attach to gluetun vpn container if realdebrid blocks IP address
    ports:
      - 3000:3000
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
