services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ${APPDATA}/prowlarr:/config
      - ${APPDATA}/prowlarr/Custom:/config/Definitions/Custom
      
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=${TP_THEME:?err}
    ports:
      - "${WEBUI_PORT_PROWLARR:?err}:9696"
  