services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
# Add Configurations for GPU Hardware Rendering Here:
#    devices:
#      - /dev/dri/renderD128:/dev/dri/renderD128
#      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${APPDATA}/plex:/config/library:/config
      - ${MEDIA}/transcode:/transcode
      - ${ZURG}:/data            ## rclone mount location from DMB must be shared to Plex container. Don't add to plex library
      - ${RIVEN}:/mnt            ## Riven symlink location from DMB must be shared to Plex container. Add to plex library
    ports:
      - 32400:32400
      - 1900:1900/udp
     # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - PLEX_CLAIM=${PLEX_CLAIM}
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
   # depends_on:                                            ## Used to delay the startup of plex to ensure the rclone mount is available.
    #  DMB:                                                 ## set to the name of the container running rclone
    #    condition: service_healthy
networks:
  default:
    name: plexarr
    external: true

