services:
    prowlarr:
        container_name: prowlarr
        deploy:
            resources:
                limits:
                    pids: 2048
        environment:
            - TZ=America/Los_Angeles
            - HOST_OS=Unraid
            - HOST_HOSTNAME=Whiskeyshits
            - HOST_CONTAINERNAME=prowlarr
            - PUID=99
            - PGID=100
            - UMASK=022
        labels:
            - net.unraid.docker.webui=http://192.168.50.69:9696
            - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
        volumes:
            - /mnt/user/appdata/prowlarr:/config:rw
        image: lscr.io/linuxserver/prowlarr