networks:
  gluetunVPN:
    name: gluetunVPN
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:?err}
          gateway: ${DOCKER_GATEWAY:?err}
services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Gluetun (qmcgaw)
  ##  Function: VPN Client
  ##
  ##  Documentation: https://github.com/qdm12/gluetun/wiki
  ##
  ###########################################################################
  ########################################################################
  ###
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetunVPN
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8800:8800 # Zurg port
      - 8888:8888/tcp # Gluetun Local Network HTTP proxy
      - 8388:8388/tcp # Gluetun Local Network Shadowsocks
      - 8388:8388/udp # Gluetun Local Network Shadowsocks
      - ${WEBUI_PORT_RDTCLIENT:?err}:6500 # WebUI Portal: RDTClient
      - ${WEBUI_PORT_PROWLARR:?err}:9696 # WebUI Portal: Prowlarr
      - ${WEBUI_PORT_BAZARR:?err}:6767 # WebUI Portal: Bazarr
      - ${WEBUI_PORT_LIDARR:?err}:8686 # WebUI Portal: Lidarr
      - ${WEBUI_PORT_DEEMIX:?err}:6595 # WebUI Portal Deemix Gui
      - ${WEBUI_PORT_RADARR:?err}:7878 # WebUI Portal: Radarr
      - ${WEBUI_PORT_READARR:?err}:8787 # WebUI Portal: Readarr
      - ${WEBUI_PORT_MYLAR3:?err}:8090 # WebUI Portal: Mylar3
      - ${WEBUI_PORT_SONARR:?err}:8989 # WebUI Portal: Sonarr
      - ${WEBUI_PORT_WHISPARR:?err}:6969 # WebUI Portal: Whisparr
      - ${WEBUI_PORT_JELLYFIN:?err}:8096 # WebUI Portal: Jellyfin
      - ${WEBUI_PORT_JELLYSEERR:?err}:5055 # WebUI Portal: Jellyseerr
      - ${WEBUI_PORT_QBITTORRENT:?err}:${WEBUI_PORT_QBITTORRENT:?err} # WebUI Portal: qBittorrent
      - ${QBIT_PORT_TCP:?err}:6881/tcp # Transmission Torrent Port TCP
      - ${QBIT_PORT_UDP:?err}:6881/udp # Transmission Torrent Port UDP
      - ${FLARESOLVERR_PORT:?err}:8191 # Service Port: FlareSolverr
      - ${TDARR_SERVER_PORT:?err}:${TDARR_SERVER_PORT:?err} # Tdarr: Server Port
      - ${WEBUI_PORT_TDARR:?err}:${WEBUI_PORT_TDARR:?err} # Tdarr: WebUI Portal
      - ${WEBUI_PORT_PLEX:?err}:32400 # WebUI Portal: Plex
      - 1900:1900/udp # DNLA Service
      - 5343:5343/udp # Plex Network Port
      - 8324:8324 # Plex Network Port
      - 32410:32410/udp # Plex Network Port
      - 32412:32412/udp # Plex Network Port
      - 32413:32413/udp # Plex Network Port
      - 32414:32414/udp # Plex Network Port
      - 32469:32469 # Plex Network Port
    volumes:
      - ${APPDATA:?err}/gluetun:/gluetun:rw
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - LOG_LEVEL=info
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_IMPLEMENTATION=auto
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - OPENVPN_ENDPOINT_IP=
      - OPENVPN_ENDPOINT_PORT=
      - OPENVPN_USER=${VPN_USERNAME:?err}
      - OPENVPN_PASSWORD=${VPN_PASSWORD:?err}
      - OPENVPN_CUSTOM_CONFIG=${OPENVPN_CUSTOM_CONFIG}
      - OPENVPN_VERSION=2.5
      - OPENVPN_VERBOSITY=1
      - OPENVPN_FLAGS=
      - OPENVPN_CIPHERS=
      - OPENVPN_AUTH=
      - OPENVPN_PROCESS_USER=
      - OPENVPN_IPV6=
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_CITIES=${SERVER_CITIES}
      - SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=
      - FIREWALL_INPUT_PORTS=
      - FIREWALL_DEBUG=off
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_SUBNET:?err}
      - DOT=off
      - DOT_PROVIDERS=cloudflare
      - DOT_PRIVATE_ADDRESS=127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112
      - DOT_VERBOSITY=1
      - DOT_VERBOSITY_DETAILS=0
      - DOT_VALIDATION_LOGLEVEL=0
      - DOT_CACHING=on
      - DOT_IPV6=off
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - UNBLOCK=
      - DNS_UPDATE_PERIOD=24h
      - DNS_ADDRESS=
      - DNS_KEEP_NAMESERVER=off
      - HTTPPROXY=on
      - HTTPPROXY_LOG=off
      - HTTPPROXY_USER=
      - HTTPPROXY_PASSWORD=
      - HTTPPROXY_STEALTH=off
      - SHADOWSOCKS=on
      - SHADOWSOCKS_LOG=off
      - SHADOWSOCKS_PASSWORD=
      - SHADOWSOCKS_CIPHER=chacha20-ietf-poly1305
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - HEALTH_TARGET_ADDRESS=github.com:443
      - HEALTH_VPN_DURATION_INITIAL=6s
      - HEALTH_VPN_DURATION_ADDITION=5s
      - UPDATER_PERIOD=0
      - PUBLICIP_FILE=/gluetun/ip
      - PUBLICIP_PERIOD=12h
      - VERSION_INFORMATION=on
      - HTTP_CONTROL_SERVER_LOG=on
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:8000
      - net.unraid.docker.icon=https://raw.githubusercontent.com/qdm12/gluetun/master/doc/logo_256.png
    # NOTE: Gluetun VPN container MUST ONLY connect to the "gluetunVPN" network
    networks:
      - gluetunVPN
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    ## Optionally, specify a specific version of pd_zurg
    # image: iampuid0/pd_zurg:2.0.0
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - ${APPDATA}/pd_zurg/config:/config
      ## Location for logs
      - ${APPDATA}/pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - ${APPDATA}/pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - ${APPDATA}/pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg     
   #   - /pd_zurg/AD:/zurg/AD   
      ## Location for rclone mount to host
      - ${RCLONE}:/data:shared       
    environment:
      - TZ=${TIMEZONE}
      ## Zurg Required Settings
      - ZURG_ENABLED=true      
      - RD_API_KEY=${REALDEBRID_API}
      ## Zurg Optional Settings
      - ZURG_LOG_LEVEL=DEBUG
     # - ZURG_VERSION=v0.9.2-hotfix.4
      - ZURG_UPDATE=true
     # - PLEX_REFRESH=true
     # - PLEX_MOUNT_DIR=/pd_zurg 
     # - ZURG_USER=
     # - ZURG_PASS=
     # - ZURG_PORT=8800   #configured in VPN
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=RD
      ## Rclone Optional Settings - See rclone docs for full list
     # - NFS_ENABLED=true
     # - NFS_PORT=8000
      - RCLONE_LOG_LEVEL=DEBUG
      - RCLONE_CACHE_DIR=/cache
      - RCLONE_DIR_CACHE_TIME=10s
      - RCLONE_VFS_CACHE_MODE=full
      - RCLONE_VFS_CACHE_MAX_SIZE=100G
      - RCLONE_ATTR_TIMEOUT=8700h
      - RCLONE_BUFFER_SIZE=32M
      - RCLONE_VFS_CACHE_MAX_AGE=4h
      - RCLONE_VFS_READ_CHUNK_SIZE=32M
      - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=1G
     # - RCLONE_TRANSFERS=8
      ## Plex Debrid Required Settings
      - PD_ENABLED=false
      ## To utilize plex_debrid with Plex, the following environment variables are required
      #- PLEX_USER=
      #- PLEX_TOKEN=
      #- PLEX_ADDRESS=
      ## To utilize plex_debrid with Jellyfin, the following environment variables are required - Note that plex_debrid will require addtional setup befor use with Jellyfin
     # - JF_ADDRESS
     # - JF_API_KEY
      ## Plex Debrid Optional Settings
     # - PD_UPDATE=true   
     # - SHOW_MENU=false
     # - SEERR_API_KEY=
     # - SEERR_ADDRESS=
      ## Special Features
      - AUTO_UPDATE_INTERVAL=12
      - DUPLICATE_CLEANUP=true
      - CLEANUP_INTERVAL=1
      - PDZURG_LOG_LEVEL=DEBUG
      - PDZURG_LOG_COUNT=2
    # Example to attach to gluetun vpn container if realdebrid blocks IP address 
    network_mode: "service:vpn" 
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
