volumes:
  ts-state-qbittorrent: null
  ts-state-rdtclient: null
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DATA:?err}/qbittorrent:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
      - ts-state-qbittorrent:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - WEBUI_PORT=${WEBUI_PORT_QBITTORRENT:?err}
      - DOCKER_MODS=${DOCKER_MODS}|ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
      - TP_THEME=${TP_THEME}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=qbittorrent
      - TAILSCALE_AUTHKEY=${TS_KEY_QBITTORRENT:?err}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=${TS_EX_ARGS}

## Do Not Change Network for qBittorrent
## qBittorrent MUST always use a VPN / Secure Internet connection
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:8088
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png
    network_mode: "container:gluetunVPN"

  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdt-client
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DATA:?err}/rdt-client/db:/data/db:rw
      - ${FOLDER_FOR_MEDIA:?err}:/data/downloads:rw
      - ts-state-rdtclient:/var/lib/tailscale
    environment:
      - TZ=America/Detroit
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Tower
      - HOST_CONTAINERNAME=rdt-client
      - PUID=99
      - PGID=100
      - UMASK=022
      - DOCKER_MODS=${DOCKER_MODS:?err}
      - TP_THEME=${TP_THEME}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=rdt-client
      - TAILSCALE_AUTHKEY=${TS_KEY_RDTCLIENT:?err}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
    # ports:
    #   - 6500:6500/tcp
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:6500
      - net.unraid.docker.icon=https://raw.githubusercontent.com/fizzyfrys/unraid-templates/main/icons/premrealldebrid.png
    network_mode: "container:gluetunVPN"
