volumes:
  ts-state-prowlarr: null
  ts-state-lidarr: null
  ts-state-radarr: null
  ts-state-sonarr: null
services:
  lidarr-on-steroids:
    container_name: lidarr-on-steroids
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - AUTOCONFIG=true
      - CLEAN_DOWNLOADS=true
      - FLAC2CUSTOM_ARGS=""
    volumes:
      - ${LSIO_APPDATA:?err}/lidarr-on-steroids:/config
      - ${LSIO_APPDATA:?err}/lidarr-on-steroids/deemix:/config_deemix
      - ${DOWNLOADS:?err}/deemix:/downloads
      - ${MEDIA:?err}/music:/music
    network_mode: container:gluetunVPN
    # Ports are disabled in containers when they are connected to VPN, as the
    # Gluetun container manages the ports for containers that connect via VPN
    #    ports:
    #      - "${WEBUI_PORT_LIDARR_ON_STEROIDS:?err}:8686"             # Configured in Gluetun VPN container
    #      - "${WEBUI_PORT_DEEMIX:?err}:6595"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ${LSIO_APPDATA:?err}/prowlarr:/config
      - ${LSIO_APPDATA:?err}/prowlarr/definitions/custom:/config/Definitions/Custom
      - ts-state-prowlarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS:?err}|ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=${TP_THEME:?err}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=prowlarr
      - TAILSCALE_AUTHKEY=${TS_KEY_PROWLARR:?err}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
    network_mode: container:gluetunVPN
    # Ports are disabled in containers when they are connected to VPN, as the
    # Gluetun container manages the ports for containers that connect via VPN
    #    ports:
    #      - "${WEBUI_PORT_PROWLARR:?err}:9696"             # Configured in Gluetun VPN container
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:9696
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
    networks: []
  lidarr:
    image: lscr.io/linuxserver/lidarr:develop
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ${LSIO_APPDATA:?err}/lidarr:/config
      - ${LSIO_APPDATA:?err}/lidarr/custom-services.d:/custom-services.d
      - ${LSIO_APPDATA:?err}/lidarr/custom-cont-init.d:/custom-cont-init.d
      - ${MEDIA:?err}:/data
      - ts-state-lidarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS:?err}|ghcr.io/themepark-dev/theme.park:lidarr
      - TP_THEME=${TP_THEME:?err}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=lidarr
      - TAILSCALE_AUTHKEY=${TS_KEY_LIDARR:?err}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    network_mode: container:gluetunVPN
    # Ports are disabled in containers when they are connected to VPN, as the
    # Gluetun container manages the ports for containers that connect via VPN
    #    ports:
    #      - "${WEBUI_PORT_LIDARR:?err}:8686"             # Configured in Gluetun VPN container
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:8686
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr-logo.png
    networks: []
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${LSIO_APPDATA:?err}/radarr:/config
      - ${LSIO_APPDATA:?err}/radarr/custom-services.d:/custom-services.d
      - ${LSIO_APPDATA:?err}/radarr/custom-cont-init.d:/custom-cont-init.d
      - ${MEDIA:?err}:/data
      - ts-state-radarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS:?err}|ghcr.io/themepark-dev/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=radarr
      - TAILSCALE_AUTHKEY=${TS_KEY_RADARR:?err}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    network_mode: container:gluetunVPN
    # Ports are disabled in containers when they are connected to VPN, as the
    # Gluetun container manages the ports for containers that connect via VPN
    #    ports:
    #      - "${WEBUI_PORT_RADARR:?err}:7878"             # Configured in Gluetun VPN container
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:7878
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png
    networks: []
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${LSIO_APPDATA:?err}/sonarr:/config
      - ${LSIO_APPDATA:?err}/sonarr/custom-services.d:/custom-services.d
      - ${LSIO_APPDATA:?err}/sonarr/custom-cont-init.d:/custom-cont-init.d
      - ${MEDIA:?err}:/data
      - ts-state-sonarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS:?err}|ghcr.io/themepark-dev/theme.park:sonarr
      - TP_THEME=${TP_THEME:?err}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=sonarr
      - TAILSCALE_AUTHKEY=${TS_KEY_SONARR:?err}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    network_mode: container:gluetunVPN
    # Ports are disabled in containers when they are connected to VPN, as the
    # Gluetun container manages the ports for containers that connect via VPN
    #    ports:
    #      - "${WEBUI_PORT_SONARR:?err}:8989"             # Configured in Gluetun VPN container
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://192.168.0.69:8989
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png
    networks: []
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    volumes:
      - ${LSIO_APPDATA:?err}/prowlarr/flaresolver:/config
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TIMEZONE:?err}
    network_mode: container:gluetunVPN
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.icon=https://raw.githubusercontent.com/FlareSolverr/FlareSolverr/master/resources/flaresolverr_logo.png

# Ports are disabled in containers when they are connected to VPN, as the
# Gluetun container manages the ports for containers that connect via VPN

#    ports:
#      - "${FLARESOLVERR_PORT:?err}:8191"             # Configured in Gluetun VPN container
