services:
  blackhole:
    image: cy01/blackhole:latest # or cy01/blackhole:beta
    container_name: blackhole
  #  network_mode: service:VPN
    ports:
      - "8282:8282" # qBittorrent
      - "8181:8181" # Proxy
    user: "1000:1000"
    volumes:
      - ${APPDATA}logs:/app/logs
      - ${DATA}:/media
      - ${DATA}/symlinks/:/media/symlinks/
      - ${APPDATA}/blackhole/config.json:/app/config.json # Config file, see below
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - QBIT_PORT=8282 # qBittorrent Port. This is optional. You can set this in the config file
      - PORT=8181 # Proxy Port. This is optional. You can set this in the config file
    restart: unless-stopped
    networks:
      - VPN
    
    depends_on:
      - rclone
#       condition: service_healthy
#        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:8181 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["./blackhole", "--config", "/app/config.json"]