services:
    DMB:
        container_name: DMB
#        network_mode: bridge
        environment:
            - HOST_OS=Unraid
            - HOST_HOSTNAME=whiskeyshits
            - HOST_CONTAINERNAME=dmb
            - TZ=America/Detroit
            - RCLONE_MOUNT_NAME=DMB
            - ZILEAN_ENABLED=true
            - ORIGIN=http://192.168.50.69:3000
            - PLEX_ADDRESS=http://192.168.50.69:32400
            - PLEX_TOKEN=claim--1V6sLYoCkepXskNdHby
            - RD_API_KEY=3EM3VDDKYJICIM3QZJ4PUQQHLTEIVV3I7FVGZJOXAUHNV3AQPVQQ
            - PGADMIN_SETUP_EMAIL=
            - PGADMIN_SETUP_PASSWORD=
            - RCLONE_DIR=/data
            - ZURG_ENABLED=true
            - ZURG_UPDATE=true
            - RIVEN_BACKEND_UPDATE=true
            - RIVEN_FRONTEND_UPDATE=true
            - FRONTEND_LOGS=ON
            - BACKEND_LOGS=ON
            - RIVEN_FRONTEND_ENABLED=true
            - RIVEN_BACKEND_ENABLED=true
            - PUID=99
            - PGID=100
            - HARD_RESET=false
        labels:
            - net.unraid.docker.webui=http://[IP]:[PORT:3000]
            - net.unraid.docker.icon=https://github.com/I-am-PUID-0/DMB/assets/36779668/d0cbc785-2e09-41da-b226-924fdfcc1f21?raw=1
        ports:
            - 3000:3000/tcp
            - 5050:5050/tcp
        volumes:
            - /mnt/user/appdata/DMB:/config:rw
            - /mnt/user/appdata/DMB/log:/log:rw
            - /mnt/user/appdata/DMB/Zurg/RD':/zurg/RD:rw
            - /mnt/user/appdata/DMB/PostgreSQL/data:/postgres_data:rw
            - /mnt/user/appdata/DMB/Riven/data:/riven/backend/data:rw
            - /mnt/user/appdata/DMB/Zilean/data/:/zilean/app/data:rw
            - /mnt/user/data/DMB/Zurg/:/data:rw,shared
            - /mnt/user/data/DMB/Riven/mnt/:/mnt:rw,shared
        devices:
            - /dev/fuse:/dev/fuse:rwm
        shm_size: 128MB
        stdin_open: true
        tty: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: iampuid0/dmb:latest