services:
  whisparr:
    image: hotio/whisparr:nightly
    container_name: whisparr
    restart: unless-stopped
    volumes:
      - ${APPDATA}/whisparr:/config
      - ${MEDIA}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
#    ports:
#      - "${WEBUI_PORT_WHISPARR:?err}:6969"             # Configured in Gluetun VPN container
