services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8099:8080
    labels:
      - net.unraid.docker.webui=http://${SERVER_IP}:8099
      - homepage.group=Utilites
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=http://${SERVER_IP}:8099
      - homepage.description=Media server
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s