services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    network_mode: container:VPN
    volumes:
      - /mnt/user/:/srv #Change to match your directory
      - ${APPDATA}/filebrowser/filebrowser.db:/database/filebrowser.db:rw #Change to match your directory
      - ${APPDATA}/filebrowser/settings.json:/config/settings.json:rw #Change to match your directory
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
   # ports:
   #   - 8095:80 #Change the port if needed
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:8095
      - net.unraid.docker.icon=https://github.com/maschhoff/docker/raw/master/filebrowser/35781395.png
      - homepage.group=Utilites
      - homepage.name=FileBrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://${SERVER_IP}:8095
      - homepage.description=Media server
    depends_on:
      DMB:
        condition: service_healthy
        restart: true