services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${APPDATA}/homearr/configs:/app/data/configs
      - ${APPDATA}/homearr/icons:/app/public/icons
      - ${APPDATA}/homearr/data:/data
    ports:
      - 7575:7575
    labels:
      - net.unraid.docker.webui=http://${SERVER_IP}:3001