#volumes:
#  ts-state-lidarr: null
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest #ghcr.io/dillydilly1990/lsio-docker-lidarr-plugins:master
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ${APPDATA:?err}/lidarr:/config
      - ${APPDATA}/lidarr/custom-cont-init.d:/custom-cont-init.d
      - ${APPDATA}/lidarr/custom-services.d:/custom-services.d
      - ${DATA}/music:/data:rw
      - ${DATA}/downloads/lidarr:/data/downloads/lidarr:rw
      
#      - ts-state-lidarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:lidarr #|${DOCKER_MODS}
      - TP_THEME=${TP_THEME}
#      - TAILSCALE_SERVE_PORT=8686
#      - TAILSCALE_SERVE_MODE=https
#      - TAILSCALE_USE_SSH=1
#      - TAILSCALE_HOSTNAME=lidarr
#      - TAILSCALE_AUTHKEY=${TS_KEY}
#      - TS_EXTRA_ARGS=${TS_EX_ARGS}
#      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    labels:
      - net.unraid.docker.webui=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr-logo.png    
      - homepage.group=Media Management
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.description=Media server
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.widget.key=${LIDARR_API}
    ports:
      - ${WEBUI_PORT_LIDARR:?err}:8686