version: "3"
services:
  lidarr-on-steroids:
    image: youegraillot/lidarr-on-steroids
    restart: unless-stopped
    ports:
      - ${WEBUI_PORT_LIDARR:?err}:8686 # Lidarr web UI
      - "6595:6595" # Deemix web UI
    volumes:
      - ${APPDATA:?err}/lidarr:/config
      - ${APPDATA:?err}/deemix:/config_deemix
      - ${DATA}/downloads/deemix:/downloads
      - ${DATA}/music:/music
    labels:
    # lidarr
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr-logo.png    
      - homepage.group=Media Management
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.description=Media server
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.widget.key=${LIDARR_API}
#      - homepage.widget.fields=["field1","field2"] # optional
    # deemix
      - homepage.group=Media Management
      - homepage.name=Deemix
      - homepage.icon=deemix.png
      - homepage.href=http://${SERVER_IP}:6595
      - homepage.description=Media server
