volumes:
  ts-state-lidarr: null
services:
  lidarr:
    image: ghcr.io/dillydilly1990/lsio-docker-lidarr-plugins:sha256-220061fdc6b6a911f10471e57b7d0993a88600f145b92c7c3b22945616ed0c5a.sig
    container_name: lidarr
    network_mode: service:VPN
    restart: unless-stopped
    volumes:
      - ${APPDATA:?err}/lidarr:/config
      - ${APPDATA}/lidarr/custom-cont-init.d:/custom-cont-init.d
      - ${APPDATA}/lidarr/custom-services.d:/custom-services.d
      - ${DATA}:/data:rw
      - ts-state-lidarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS}|ghcr.io/themepark-dev/theme.park:lidarr
      - TP_THEME=${TP_THEME}
      - TAILSCALE_SERVE_PORT=8686
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=lidarr
      - TAILSCALE_AUTHKEY=${TS_KEY}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lidarr-logo.png    
      - homepage.group=Media Management
      - homepage.name=Lidarr
      - homepage.icon=lidarr.png
      - homepage.href=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.description=Media server
      - homepage.widget.type=lidarr
      - homepage.widget.url=http://${SERVER_IP}:${WEBUI_PORT_LIDARR}
      - homepage.widget.key=${LIDARR_API}
#      - homepage.widget.fields=["field1","field2"] # optional
#    ports:
#      - ${WEBUI_PORT_LIDARR:?err}:8686
    depends_on:
      zurg:
        condition: service_healthy
        restart: true