#volumes:
#  ts-state-radarr: null
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${APPDATA:?err}/radarr:/config
      - ${APPDATA}/radarr/custom-cont-init.d:/custom-cont-init.d
      - ${APPDATA}/radarr/custom-services.d:/custom-services.d
      - ${DATA}:/data:rw
#      - ts-state-radarr:/var/lib/tailscale
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr #|${DOCKER_MODS}
      - TP_THEME=${TP_THEME}
#      - TAILSCALE_SERVE_PORT=8686
#      - TAILSCALE_SERVE_MODE=https
#      - TAILSCALE_USE_SSH=1
#      - TAILSCALE_HOSTNAME=Radarr
#      - TAILSCALE_AUTHKEY=${TS_KEY}
#      - TS_EXTRA_ARGS=${TS_EX_ARGS}
#      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    labels:
      - net.unraid.docker.webui=http://${SERVER_IP}:${WEBUI_PORT_RADARR}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png
      - homepage.group=Media Management
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://${SERVER_IP}:${WEBUI_PORT_RADARR}
      - homepage.description=Media server
      - homepage.widget.type=radarr
      - homepage.widget.url=http://${SERVER_IP}:${WEBUI_PORT_RADARR}
      - homepage.widget.key=${RADARR_API}
    ports:
      - ${WEBUI_PORT_RADARR:?err}:7878