services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
#    network_mode: service:VPN
    restart: unless-stopped
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
   ports:
      - 5572:5572
    volumes:
      - /mnt/user/RealDebrid:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - ${APPDATA}/zurg/rclone.conf:/config/rclone/rclone.conf    
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-cache-mode full"
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:5572
      - net.unraid.docker.icon=https://raw.githubusercontent.com/rclone/rclone/master/graphics/logo/logo_symbol/logo_symbol_color_256px.png
      - homepage.group=Core Services
      - homepage.name=Rclone
      - homepage.icon=rclone.png
      - homepage.href=http://${SERVER_IP}:5572
      - homepage.description=Media server