volumes:
  ts-state-sonarr: null
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:VPN
    restart: unless-stopped
    volumes:
      - ${APPDATA:?err}/sonarr:/config
      - ${MEDIA}/tv:/data/tv
      - ${DOWNLOADS}/symlinks/sonarr:/data/symlinks
      - /mnt/user/RealDebrid/__all__:/data/torrents
      - ts-state-sonarr:/var/lib/tailscale
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=${DOCKER_MODS}|ghcr.io/themepark-dev/theme.park:sonarr
      - TP_THEME=${TP_THEME}
      - TAILSCALE_SERVE_PORT=8989
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=Sonarr
      - TAILSCALE_AUTHKEY=${TS_KEY}
      - TS_EXTRA_ARGS=${TS_EX_ARGS}
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:${WEBUI_PORT_SONARR}
      - net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png
      - homepage.group=Media Management
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://${SERVER_IP}:${WEBUI_PORT_SONARR}
      - homepage.description=Media server
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://${SERVER_IP}:${WEBUI_PORT_SONARR}
      - homepage.widget.key=${SONARR_API}
#      - homepage.widget.fields=["field1","field2"] # optional
#    ports:
#      - "${WEBUI_PORT_SONARR:?err}:8989"             
    depends_on:
      zurg:
        condition: service_healthy
        restart: true