services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    deploy:
      resources:
        limits:
          pids: 2048
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA}/tsdproxy:/data,rw
      - ${APPDATA}/tsdproxy/config:/config,rw
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=${TS_KEY}
      # Address of docker server (access to example.com ports)
      - TSDPROXY_HOSTNAME=${SERVER_IP}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped