services:
    dmb:
        container_name: dmb
        network_mode: bridge
        environment:
            - TZ=America/Los_Angeles
            - HOST_OS=Unraid
            - HOST_HOSTNAME=whiskeyshits
            - HOST_CONTAINERNAME=dmb
            - TZ'='America/Detroit
            - RCLONE_MOUNT_NAME'='RD
            - ZILEAN_ENABLED'='true
            - ORIGIN'='http://192.168.50.69:3000
            - PLEX_ADDRESS'='http://192.168.50.69:32400
            - PLEX_TOKEN'='claim-yhFxybKKZixMcygtUBcc
            - RD_API_KEY'='3EM3VDDKYJICIM3QZJ4PUQQHLTEIVV3I7FVGZJOXAUHNV3AQPVQQ
            - PGADMIN_SETUP_EMAIL'='
            - PGADMIN_SETUP_PASSWORD'='
            - ZURG_ENABLED'='true
            - ZURG_UPDATE'='true
            - RIVEN_BACKEND_UPDATE'='true
            - RIVEN_FRONTEND_UPDATE'='true
            - FRONTEND_LOGS'='ON
            - BACKEND_LOGS'='ON
            - RIVEN_FRONTEND_ENABLED'='true
            - RIVEN_BACKEND_ENABLED'='true
            - PUID'='99
            - PGID'='100
            - HARD_RESET'='false
        labels:
            - net.unraid.docker.managed=dockerman
            - net.unraid.docker.webui='http://[IP]:[PORT:3000]'
            - net.unraid.docker.icon='https://github.com/I-am-PUID-0/DMB/assets/36779668/d0cbc785-2e09-41da-b226-924fdfcc1f21?raw=1'
        ports:
            - 3000:3000/tcp
            - 5050:5050/tcp
        volumes:
            - /mnt/user/appdata/DMB:/config:rw
            - /mnt/user/appdata/DMB/log:/log:rw
            - /mnt/user/appdata/DMB/Zurg/RD:/zurg/RD:rw
            - /mnt/user/appdata/DMB/PostgreSQL/data:/postgres_data:rw
            - /mnt/user/appdata/DMB/Riven/data:/riven/backend/data:rw
            - /mnt/user/DMB/zilean/data:/zilean/app/data:rw
            - /mnt/user/DMB/Zurg/mnt:/data:rw,shared
            - /mnt/user/DMB/Riven/mnt:/mnt:rw
        devices:
            - /dev/fuse:/dev/fuse:rwm
        stdin_open: true
        tty: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: "'iampuid0/dmb:latest'"  
  
  DMB:
    container_name: DMB
    image: iampuid0/dmb:latest                                       ## Optionally, specify a specific version of DMB w/ image: iampuid0/dmb:2.0.0
    stop_grace_period: 30s                                           ## Adjust as need to allow for graceful shutdown of the container
    stdin_open: true                                                 ## docker run -i
    tty: true                                                        ## docker run -t
    volumes:
    # config dirs
      - ${APPDATA}/DMB/config:/config                     ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup.
      - ${APPDATA}/DMB/log:/log                           ## Location for logs
      - ${APPDATA}/DMB/Zurg/RD:/zurg/RD                   ## Location for Zurg RealDebrid active configuration
      - ${APPDATA}/DMB/PostgreSQL/data:/postgres_data     ## Location for PostgreSQL database if using Riven
      - ${APPDATA}/DMB/Zilean/data:/zilean/app/data       ## Location for Zilean data if using Riven
      - ${APPDATA}/DMB/Riven/data:/riven/backend/data     ## Location for Riven backend data
    # media dirs
      - ${RCLONE}:/data:shared           ## Location for rclone mount to host
      - ${SYMLINKS}:/mnt                  ## Location for Riven symlinks

    environment:
      - TZ=${TIMEZONE:?err}
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - COLOR_LOG_ENABLED=true
      - PLEX_TOKEN=${PLEX_CLAIM}
      - PLEX_ADDRESS=${SERVER_IP}:32400
      - ZURG_ENABLED=false
      - RD_API_KEY=${REALDEBRID_API}
      - RCLONE_MOUNT_NAME=DMB
      - ZILEAN_ENABLED=false
      - RIVEN_ENABLED=true
      - ORIGIN=${SERVER_IP}:3000                                  ## See Riven documentation for more details
    # network_mode: container:gluetun                            ## Example to attach to gluetun vpn container if realdebrid blocks IP address
    ports:
      - 3000:3000
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui=http://${SERVER_IP}:3000
      - net.unraid.docker.icon=https://github.com/rivenmedia/riven/blob/main/assets/riven-light.png
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - no-new-privileges
