services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${APPDATA:?err}/radarr:/config
      - ${MEDIA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
      - TP_THEME=${TP_THEME}
    ports:
      - "${WEBUI_PORT_RADARR:?err}:7878"             # Configured in Gluetun VPN container
